Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4
r3live_vio:
   camera_intrinsic:          # 相机内参
      [863.4241, 0.0, 640.6808,
      0.0,  863.4171, 518.3392,
      0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [-0.1080, 0.1050, -1.2872e-04, 5.7923e-05, -0.0222]  # 畸变系数k1, k2, p1, p2, k3
# 相机外参
# 邹标的
   # camera_ext_R:
   #       [0.0621021,-0.998023,-0.00968298,
   #          -0.0184797,0.00855026,-0.999793,
   #          0.997899,0.0622682,-0.0179121]
   # camera_ext_t: [0.353419,-0.0248936,0.653306] 

# 杨苏桥标的
   # camera_ext_R:
   #       [0.11984,-0.991845,-0.0433864,
   #          -0.141261,0.0262214,-0.989625,
   #          0.982692,0.124725,-0.136967]
   # camera_ext_t: [-0.752334,0.730933,-0.845027] 


# 原作者
   camera_ext_R:
         [-0.00113207, -0.0158688, 0.999873,
            -0.9999999,  -0.000486594, -0.00113994,
            0.000504622,  -0.999874,  -0.0158682]

   # camera_ext_R:
   #       [0.00113207, 0.0158688, -0.999873,
   #          0.9999999,  0.000486594, 0.00113994,
   #          -0.000504622,  0.999874,  0.0158682]


   camera_ext_t: [-0.353419,0.0248936,0.653306] 

r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 4          # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   #  体素大小
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30